service: poc-serverless

frameworkVersion: ">=2.52.0 <3.0.0"

plugins:
  - serverless-python-requirements
  - serverless-stage-manager
  - serverless-plugin-log-retention
  - serverless-domain-manager
  - serverless-offline
  - serverless-prune-plugin
  - serverless-localstack

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 512
  timeout: 20
  endpointType: regional

  stage: ${opt:stage, 'dev'}

  lambdaHashingVersion: "20201221"

custom:
  # Used by ternary operators
  true: true
  accountId: "0000000000"

  stages:
    - local
    - dev
    - qa
    - prod

  customStageDomain:
    enabled:
      local: false

  dotenv:
    path: .env.local

  customDomain:
    domainName: ''
    certificateName: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'
    autoDomain: true
    securityPolicy: tls_1_2
    apiType: rest
    enabled: ${self:custom.customStageDomain.enabled.${opt:stage}, self:custom.true}

  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: false

  logRetentionInDays: 14

  prune:
    automatic: true
    number: 5

  serverless-offline:
    httpPort: 8081
    printOutput: false
    noPrependStageInUrl: true

  localstack:
    stages:
      - local
    host: http://localstack
    edgePort: 4566
    autostart: false
    lambda:
      mountCode: false # should be true


package:
  patterns:
    - "!*/**"
    - "!*"
    - "!**/__pycache__"
    - "src/**"
    - "!src/tests/**"
  excludeDevDependencies: true

functions:
  units:
    handler: src/serverless/main.lambda_handler
    events:
      - http:
          path: version
          method: get
